# The URL the site will be built for
base_url = "https://umwacm.github.io/pcg"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = false

title = "UMW ACM Programming Code Golf"
description = ""
# the default language, used in RSS and coming i18n
default_language = "en"
theme = "feather"
[extra]
# Put all your custom variables here
