name = "feather"
description = "A modern blog theme"
license = "MIT"
homepage = "https://github.com/piedoom/feather"
min_version = "0.2"

[extra]
feather_header_image = "/theme_images/default.gif"
feather_disqus_code = ""
feather_donate_link = ""
feather_analytics = ""

[author]
name = "Chad Baxter"
homepage = "LogoiLab.github.io"
